# Try-Except:

#Finally :
try:
   print(x)

except:
   print("Somthing Wrong!")
finally:
   print("Try is finished!")
   
